# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161016_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
